---
inputs:
  - name: container_directory
    type: BaseTypeString


description: |
  Move etc/hosts and link it to etc/hosts.source, so it can be used in Docker

  Inputs:
    container_directory - name of the container directory
  Outputs:
    None

executor:
  type: bash
  arguments:
    - "@container_directory.value@"
  payload: |
    CONTAINER_DIRECTORY=$1
   
    cd $CONTAINER_DIRECTORY 

    # Move hosts, so it can be used in docker 
    mv etc/hosts etc/hosts.source
    ln -s etc/hosts.source etc/hosts
